### ISSUE TITLE
Moving ZIP to its place

### ISSUE THREAD

**Issue by szepeviktor** [Gaya/ab-testing-for-wp#20]
Please consider moving `ab-testing-for-wp.zip` file to [releases](https://github.com/Gaya/ab-testing-for-wp/releases)
Of course there must be [tagged releases](https://github.com/Gaya/ab-testing-for-wp/blob/master/README.txt#L81-L121) to attach files to them :)

It could be completely removed https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository making the repository **much smaller**.

**Comment by szepeviktor** [comment]
You could use `npm archive` to upload that ZIP using GitHub API.
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by Gaya** [comment]
Interesting idea. While a .zip is not sensitive data, I agree with moving it out of the repo as it is generated anyway. Will look into it, thanks for the suggestion.

**Comment by szepeviktor** [comment]
A list of tagging commands

```bash
git tag v1.0.0 97e37ef345448156e2cd5b930f74e5cd2321edde
git tag v1.1.0 400431ac56d4bd7babb08a80e52ff49a5d76df10
git tag v1.2.2 55e87b46f9e8a4bf59f6b25505ec5c92f7442854
git tag v1.3.1 80d273af5b0ce8b206fcc0942cb4a7643c1a3806
git tag v1.4.0 b9c9b1120b6e4c074ca2c0da06bcec40a9858869
git tag v1.5.0 086b4c2ae8ef378f6a12a522c107a731306c9041
git tag v1.6.0 db6eebea30521bb8c1a4d3e94e5d8b370cff7009
git tag v1.7.0 e5c9691a554bec21b2ab5324ee26ef285a7583b7
git tag v1.8.1 683b372624b7713a866560ad929961636a960873
git tag v1.9.0 ebf06bf9bc674be45e899e3e05b4d5a7215ae6a7
git tag v1.9.1 9ff75a79d481dabb4125779e1e53630fba1780e5
git tag v1.10.0 f264e2f29fb38e7a75e0b8d44eb65ebb67b36b49
```

**Comment by Gaya** [comment]
This has been resolved. All new tags will automatically get a zipped version of the project delivered through releases:

https://github.com/Gaya/ab-testing-for-wp/releases/tag/v1.10.0

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
As only very few people forked this repo please consider removing the ZIP and benefit from the repo size reduction!

**Comment by Gaya** [comment]
I was only able to release tags like this from when the `release.yml` was in place.

I'll keep the repository as is.

Thanks for the suggestion though
