### ISSUE TITLE
Commit authors

### ISSUE THREAD

**Issue by szepeviktor** [Gaya/ab-testing-for-wp#21]
@Gaya Could it that you use your `@gmail.com` - non-GitHub - address in your git client?

**Comment by Gaya** [comment]
The commits were set to my old email address I was using for GitHub. I changed the commits to reflect my current email address. Good catch.

GitHub has a pretty nice write up on how to do this:
https://help.github.com/en/github/using-git/changing-author-info

**Comment by Gaya** [comment]
Damn! Seems like the process removed your pull requests. Reverting this for now.

**Comment by szepeviktor** [comment]
Done: https://github.com/Gaya/ab-testing-for-wp/commits/master
