### ISSUE TITLE
REST API endpoints are missing permission_callback in WordPress 5.5

### ISSUE THREAD

**Issue by maxharland** [Gaya/ab-testing-for-wp#67]
Due to [recent changes to the Wordpress Rest API](https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/#callback) the following warning is shown:

> Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>ab-testing-for-wp/v1/ab-test</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback.

Plugin version: 1.18.2
Wordpress version: 5.5.1

**Comment by daviddarke** [comment]
@maxharland and @Gaya I've started a PR for this: https://github.com/Gaya/ab-testing-for-wp/pull/68

**Comment by Gaya** [comment]
Thanks for contributing. 

Haven’t had the chance to update to the latest WordPress version yet.

The e2e tests in the CI are failing because of this I am guessing.

Would be great if you could take a look.

**Comment by daviddarke** [comment]
Yeah sure! I'll take a look.

**Comment by daviddarke** [comment]
I've dropped back to your `master` and downgraded WP and still getting the same failures on the CI. @Gaya Can you just test master on your side to see if you are getting issues.

One for example from "ab-testing.spec.ts"/"Can change conditions of variants":

<img width="426" alt="Screenshot 2020-10-30 at 15 47 33" src="https://user-images.githubusercontent.com/1636310/97726551-3bdbb280-1ac7-11eb-8836-290c1c093299.png">

Very similar to CI.

**Comment by JJJ** [comment]
Merged into the 1.19 release branch. 🙏
